---
- name: Installer Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes
  become: true

- name: Copier la configuration du site par défaut
  template:
    src: default.j2
    dest: /etc/nginx/sites-available/default
  notify: Recharger Nginx
  become: true

- name: Activer le site par défaut
  file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    state: link
  notify: Recharger Nginx
  become: true

- name: S'assurer que Nginx est démarré et activé
  service:
    name: nginx
    state: started
    enabled: true
  become: true
