---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: "docker.io/pycontribs/ubuntu:latest"
    pre_build_image: true
provisioner:
  name: ansible
  role_name_check: false
verifier:
  name: ansible